#!/bin/sh

# usage: ./new-post My Amazing Blog Post
# creates a new index file at content/blog/my-amazing-blog-post with the frontmatter partially filled out

title=$@

slug=$(echo "${title}" | iconv -t ascii//TRANSLIT | sed -r s/[^a-zA-Z0-9]+/-/g | sed -r s/^-+\|-+$//g | tr A-Z a-z)
new_path="content/blog/${slug}"

mkdir $new_path

cat <<EOF > $new_path/index.md
---
title: ${title}
date: $(date -u +%Y-%m-%dT%H:%M:%SZ)
description: Post description
tags:
  - tech
---
EOF
